<main class="main contenedor">
        <div class="imagen-nosotros">
            <div class="modal">
            </div>
            <h2>Nosotros</h2>
        </div>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos nihil suscipit delectus praesentium natus possimus explicabo sint, ratione vero earum ad blanditiis maxime porro numquam quae placeat dolores neque nemo. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas fugiat tempora itaque placeat blanditiis, similique aspernatur quis eligendi? Rerum et consequatur eius officia voluptatibus nam nemo sed, quibusdam beatae corrupti? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deserunt laboriosam ea veritatis vel? Tempora deserunt commodi aspernatur labore soluta. Placeat nesciunt ab eligendi ratione, amet esse assumenda sit eum similique. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Explicabo vero itaque sed animi corporis quia, doloremque, sint illo beatae a ullam nesciunt sit facilis sequi? Ipsum dicta beatae cum laborum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam illum debitis enim at est? Asperiores voluptas excepturi perferendis fugiat! Animi quos, placeat harum laborum inventore architecto eveniet officiis beatae nobis!Lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem natus in hic illum a libero sapiente repellat accusantium cupiditate officia molestias odio quod, ducimus consequuntur pariatur totam veniam dicta ullam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam, sunt quasi? Ducimus facere saepe eaque, earum vero sapiente aliquam voluptates suscipit optio eum, quas quis sint dicta culpa quae velit.</p>
        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eum, quia soluta! Odio ea beatae quasi. Quo, minima harum rerum quae laborum, debitis qui modi omnis, rem voluptatum cum explicabo alias! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Vitae quisquam alias quae quos fugiat in, optio rerum temporibus perferendis culpa voluptatibus magnam quasi voluptate? Magni deleniti obcaecati cupiditate voluptas sit? Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, enim aspernatur. Vitae ipsam dicta repellendus temporibus! Aliquam qui cumque at, in voluptate esse, obcaecati dolor nemo, veniam sapiente saepe molestiae. Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur tempora incidunt aliquid minus ut optio sunt eligendi ipsa maiores nihil ullam totam iste autem, vero, dolores vel alias facere! Soluta.</p>
        <a href="/equipo" class="boton-verde">Conoce a Nuestro equipo</a>
    </main>